#!/usr/bin/env python3
"""Stage exactly this task's work; leave the pre-existing stale dist pages unstaged.

site/dist was rebuilt, so git sees three kinds of change:
  1. the stylesheet + inlined rail JS  -- this task's work
  2. 26 content pages that a rebuild of PRISTINE HEAD also rewrites -- pre-existing staleness
     (briefs shipped after the last dist rebuild), which must NOT ride along in a layout commit
  3. pipeline/state.json -- pipeline bookkeeping regenerated by the build

(1) is staged. (2) and (3) are left unstaged and named in the commit body, so the change is
reviewable as a layout diff rather than as a content diff.
"""
import subprocess
import sys

WT = "/Users/shawnlin/parsnips/.worktrees/t_140a0b87"
BASE = "/Users/shawnlin/.hermes/profiles/dev_parsnips/cache/scratch/baseline-140a0b87"


def git(*args, cwd=WT):
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True)


# (2): the pages a pristine rebuild rewrites -- derived, not hard-coded.
out = git("diff", "--numstat", "--", "site/dist/sittings/", cwd=BASE).stdout
stale = sorted(line.split("\t")[2] for line in out.splitlines()
               if len(line.split("\t")) == 3)

print(f"pre-existing stale pages (left unstaged): {len(stale)}")
for s in stale:
    print(f"   {s}")

# Stage the source of truth and this task's new material.
for path in ["site/build_site.py", "site/dist/theme.css", "tools", "docs/layout-after",
             "docs/layout-audit"]:
    print(git("add", "--", path).stderr.strip() or f"staged {path}")

# Stage the sitting pages, then unstage the stale ones.
print(git("add", "--", "site/dist/sittings").stderr.strip() or "staged site/dist/sittings")
if stale:
    r = git("reset", "-q", "--", *stale)
    print(f"unstaged {len(stale)} stale pages (exit={r.returncode})")
    if r.stderr.strip():
        print("   ", r.stderr.strip()[:200])

print()
print("=== staged summary ===")
print(git("diff", "--cached", "--stat").stdout.strip().splitlines()[-1])
print()
print("=== left unstaged ===")
for line in git("status", "--short").stdout.splitlines():
    if not line.startswith("M ") and not line.startswith("A "):
        print("   ", line)

sys.exit(0)
